-- RegisterNetEvent('luna_newbie:client:newbieGift', function()
--     TriggerEvent("mythic_progbar:client:progress", {
-- 		name = "newbiegift",
-- 		duration = 3000,
-- 		label = "Đang mở quà",
-- 		useWhileDead = false,
-- 		canCancel = true,
-- 		controlDisables = {
-- 			disableMovement = true,
-- 			disableCarMovement = true,
-- 			disableMouse = false,
-- 			disableCombat = true,
-- 		},	
-- 		animation = {
-- 			animDict = "missheistdockssetup1clipboard@idle_a",
-- 			anim = "idle_a",
-- 		},		
-- 		--[[prop = {
-- 			model = "prop_paper_bag_small",
-- 		}]]		
-- 		},function(status)
-- 		if not status then
-- 			TriggerServerEvent('luna_newbie:newbieGift')
-- 		end
-- 	end)
-- end)